#!/usr/bin/env python3
"""
Pipeline Generator Utilities
Generated by Claude Code skill:generate-azure-pipelines
"""

from typing import Dict, List, Any
import re


def get_vm_image(runtime: str, version: str) -> str:
    """
    Get the appropriate Azure Pipelines VM image for the runtime.

    Args:
        runtime: Runtime name (python, nodejs, dotnet, docker)
        version: Runtime version

    Returns:
        VM image name for Azure Pipelines
    """
    runtime_lower = runtime.lower()

    # Default to ubuntu-latest for most runtimes
    vm_images = {
        "python": "ubuntu-latest",
        "nodejs": "ubuntu-latest",
        "dotnet": "windows-latest" if version.startswith("4.") else "ubuntu-latest",
        "docker": "ubuntu-latest",
    }

    return vm_images.get(runtime_lower, "ubuntu-latest")


def get_artifact_name(project_name: str) -> str:
    """
    Generate artifact name from project name.

    Args:
        project_name: Project name

    Returns:
        Sanitized artifact name
    """
    # Remove special characters and convert to lowercase
    artifact_name = re.sub(r'[^a-zA-Z0-9-]', '-', project_name).lower()
    return artifact_name


def get_bicep_resource_prefix(project_name: str) -> str:
    """
    Generate Bicep resource prefix from project name.

    Args:
        project_name: Project name

    Returns:
        Resource prefix (max 10 chars, lowercase, alphanumeric)
    """
    # Remove special characters, convert to lowercase, limit to 10 chars
    prefix = re.sub(r'[^a-z0-9]', '', project_name.lower())[:10]
    return prefix


def validate_pipeline_config(config: Dict[str, Any]) -> List[str]:
    """
    Validate pipeline configuration.

    Args:
        config: Pipeline configuration dictionary

    Returns:
        List of validation error messages (empty if valid)
    """
    errors = []

    # Required fields
    required_fields = ['project_name', 'runtime', 'deployment_target', 'environments']
    for field in required_fields:
        if field not in config:
            errors.append(f"Missing required field: {field}")

    # Validate runtime
    valid_runtimes = ['python', 'nodejs', 'dotnet', 'docker']
    if 'runtime' in config and config['runtime'].lower() not in valid_runtimes:
        errors.append(f"Invalid runtime: {config['runtime']}. Must be one of {valid_runtimes}")

    # Validate environments
    if 'environments' in config and not isinstance(config['environments'], list):
        errors.append("Environments must be a list")

    if 'environments' in config and len(config['environments']) == 0:
        errors.append("At least one environment is required")

    # Validate deployment target
    valid_targets = ['function-app', 'app-service', 'container-instances', 'aks', 'static-web-app']
    if 'deployment_target' in config and config['deployment_target'] not in valid_targets:
        errors.append(f"Invalid deployment target: {config['deployment_target']}. Must be one of {valid_targets}")

    return errors


def get_service_connection_name(environment: str, project_name: str) -> str:
    """
    Generate service connection name.

    Args:
        environment: Environment name (development, staging, production)
        project_name: Project name

    Returns:
        Service connection name
    """
    return f"{project_name}-{environment}-connection"


def get_variable_group_name(environment: str, project_name: str) -> str:
    """
    Generate variable group name.

    Args:
        environment: Environment name
        project_name: Project name

    Returns:
        Variable group name
    """
    return f"{project_name}-{environment}-variables"


def get_environment_resource_name(environment: str) -> str:
    """
    Get Azure DevOps environment resource name.

    Args:
        environment: Environment name

    Returns:
        Environment resource name
    """
    # Map friendly names to resource names
    environment_mapping = {
        "development": "development",
        "dev": "development",
        "staging": "staging",
        "stage": "staging",
        "production": "production",
        "prod": "production",
    }

    return environment_mapping.get(environment.lower(), environment.lower())


def generate_bicep_params_config(environment: str, location: str = "eastus") -> Dict[str, str]:
    """
    Generate Bicep parameters configuration for an environment.

    Args:
        environment: Environment name
        location: Azure region

    Returns:
        Dictionary of Bicep parameters
    """
    return {
        "environment": environment.lower(),
        "location": location,
    }


def get_deployment_condition(environment: str, source_branch: str = "main") -> str:
    """
    Generate pipeline condition for environment deployment.

    Args:
        environment: Environment name
        source_branch: Git branch that triggers deployment

    Returns:
        Pipeline condition expression
    """
    conditions = {
        "development": "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))",
        "staging": "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))",
        "production": "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))",
    }

    env_lower = environment.lower()
    return conditions.get(env_lower, f"and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/{source_branch}'))")


def get_bicep_resource_name_patterns() -> Dict[str, str]:
    """
    Get standard Bicep resource naming patterns.

    Returns:
        Dictionary of resource type to naming pattern
    """
    return {
        "storage": "st",
        "function-app": "func",
        "app-service": "app",
        "key-vault": "kv",
        "sql-server": "sql",
        "cosmos-db": "cosmos",
        "app-insights": "appi",
        "app-service-plan": "plan",
    }


if __name__ == "__main__":
    # Example usage
    print("Pipeline Generator Utilities")
    print("=" * 50)

    # Example configuration
    config = {
        "project_name": "my-app",
        "runtime": "python",
        "deployment_target": "function-app",
        "environments": ["development", "production"]
    }

    # Validate
    errors = validate_pipeline_config(config)
    if errors:
        print("Validation errors:")
        for error in errors:
            print(f"  - {error}")
    else:
        print("Configuration valid!")
        print(f"VM Image: {get_vm_image('python', '3.11')}")
        print(f"Artifact Name: {get_artifact_name(config['project_name'])}")
        print(f"Resource Prefix: {get_bicep_resource_prefix(config['project_name'])}")
        print(f"Variable Group: {get_variable_group_name('development', config['project_name'])}")
