// Bicep Parameters for {{PROJECT_NAME}} - {{ENVIRONMENT}} Environment
// Generated by Claude Code skill:generate-azure-bicep

using './main.bicep'

param environment = '{{ENVIRONMENT}}'
param location = '{{LOCATION}}'
param resourcePrefix = '{{RESOURCE_PREFIX}}'
