// Main Bicep Template for {{PROJECT_NAME}}
// Generated by Claude Code skill:generate-azure-bicep
// Uses Azure Verified Modules (AVM)

targetScope = '{{TARGET_SCOPE}}'

@description('Environment name (development, staging, production)')
param environment string

@description('Azure region for resources')
param location string = {{LOCATION_DEFAULT}}

@description('Resource naming prefix')
param resourcePrefix string = '{{RESOURCE_PREFIX}}'

// Common tags for all resources
var tags = {
  environment: environment
  project: '{{PROJECT_NAME}}'
  managedBy: 'bicep-avm'
}

{{#INCLUDE_RESOURCE_GROUP}}
// Resource Group
resource rg 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: '${resourcePrefix}-${environment}-rg'
  location: location
  tags: tags
}

{{/INCLUDE_RESOURCE_GROUP}}
{{#INCLUDE_LOG_ANALYTICS}}
// Log Analytics Workspace (for diagnostic settings)
module logAnalytics 'br/public:avm/res/operational-insights/workspace:{{LOG_ANALYTICS_VERSION}}' = {
  {{#RESOURCE_GROUP_SCOPE}}
  scope: rg
  {{/RESOURCE_GROUP_SCOPE}}
  name: 'logAnalyticsDeployment'
  params: {
    name: '${resourcePrefix}-${environment}-logs'
    location: location
    tags: tags
  }
}

{{/INCLUDE_LOG_ANALYTICS}}
{{#INCLUDE_STORAGE}}
// Storage Account
module storageAccount 'br/public:avm/res/storage/storage-account:{{STORAGE_VERSION}}' = {
  {{#RESOURCE_GROUP_SCOPE}}
  scope: rg
  {{/RESOURCE_GROUP_SCOPE}}
  name: 'storageAccountDeployment'
  params: {
    name: 'st${environment}${uniqueString({{UNIQUE_STRING_INPUT}})}'
    location: location
    tags: tags
    skuName: environment == 'production' ? 'Standard_GRS' : 'Standard_LRS'
    kind: 'StorageV2'
    accessTier: 'Hot'
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    {{#INCLUDE_DIAGNOSTICS}}
    diagnosticSettings: [
      {
        workspaceResourceId: logAnalytics.outputs.resourceId
        logCategoriesAndGroups: [
          {
            categoryGroup: 'allLogs'
          }
        ]
      }
    ]
    {{/INCLUDE_DIAGNOSTICS}}
  }
}

{{/INCLUDE_STORAGE}}
{{#INCLUDE_KEY_VAULT}}
// Key Vault
module keyVault 'br/public:avm/res/key-vault/vault:{{KEY_VAULT_VERSION}}' = {
  {{#RESOURCE_GROUP_SCOPE}}
  scope: rg
  {{/RESOURCE_GROUP_SCOPE}}
  name: 'keyVaultDeployment'
  params: {
    name: 'kv-${environment}-${uniqueString({{UNIQUE_STRING_INPUT}})}'
    location: location
    tags: tags
    sku: environment == 'production' ? 'premium' : 'standard'
    enableRbacAuthorization: true
    {{#INCLUDE_DIAGNOSTICS}}
    diagnosticSettings: [
      {
        workspaceResourceId: logAnalytics.outputs.resourceId
        logCategoriesAndGroups: [
          {
            categoryGroup: 'allLogs'
          }
        ]
      }
    ]
    {{/INCLUDE_DIAGNOSTICS}}
  }
}

{{/INCLUDE_KEY_VAULT}}
{{#INCLUDE_APP_INSIGHTS}}
// Application Insights
module appInsights 'br/public:avm/res/insights/component:{{APP_INSIGHTS_VERSION}}' = {
  {{#RESOURCE_GROUP_SCOPE}}
  scope: rg
  {{/RESOURCE_GROUP_SCOPE}}
  name: 'appInsightsDeployment'
  params: {
    name: '${resourcePrefix}-${environment}-appi'
    location: location
    tags: tags
    applicationType: 'web'
    {{#INCLUDE_LOG_ANALYTICS}}
    workspaceResourceId: logAnalytics.outputs.resourceId
    {{/INCLUDE_LOG_ANALYTICS}}
  }
}

{{/INCLUDE_APP_INSIGHTS}}
{{#INCLUDE_FUNCTION_APP}}
// App Service Plan for Function App
module appServicePlan 'br/public:avm/res/web/serverfarm:{{APP_SERVICE_PLAN_VERSION}}' = {
  {{#RESOURCE_GROUP_SCOPE}}
  scope: rg
  {{/RESOURCE_GROUP_SCOPE}}
  name: 'appServicePlanDeployment'
  params: {
    name: '${resourcePrefix}-${environment}-plan'
    location: location
    tags: tags
    sku: {
      name: environment == 'production' ? 'P1v2' : 'B1'
      tier: environment == 'production' ? 'PremiumV2' : 'Basic'
    }
    kind: 'linux'
    reserved: true
  }
}

// Function App
module functionApp 'br/public:avm/res/web/site:{{WEB_SITE_VERSION}}' = {
  {{#RESOURCE_GROUP_SCOPE}}
  scope: rg
  {{/RESOURCE_GROUP_SCOPE}}
  name: 'functionAppDeployment'
  params: {
    name: '${resourcePrefix}-${environment}-func'
    location: location
    tags: tags
    kind: 'functionapp,linux'
    serverFarmResourceId: appServicePlan.outputs.resourceId
    siteConfig: {
      linuxFxVersion: '{{RUNTIME_VERSION}}'
      appSettings: [
        {
          name: 'AzureWebJobsStorage'
          value: 'DefaultEndpointsProtocol=https;AccountName=${storageAccount.outputs.name};AccountKey=${storageAccount.outputs.keys[0].value}'
        }
        {
          name: 'FUNCTIONS_EXTENSION_VERSION'
          value: '~4'
        }
        {
          name: 'FUNCTIONS_WORKER_RUNTIME'
          value: '{{WORKER_RUNTIME}}'
        }
        {{#INCLUDE_APP_INSIGHTS}}
        {
          name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          value: appInsights.outputs.instrumentationKey
        }
        {{/INCLUDE_APP_INSIGHTS}}
      ]
    }
    httpsOnly: true
  }
}

{{/INCLUDE_FUNCTION_APP}}
// Outputs
{{#INCLUDE_RESOURCE_GROUP}}
output resourceGroupName string = rg.name
output resourceGroupId string = rg.id
{{/INCLUDE_RESOURCE_GROUP}}
{{#INCLUDE_STORAGE}}
output storageAccountName string = storageAccount.outputs.name
output storageAccountId string = storageAccount.outputs.resourceId
{{/INCLUDE_STORAGE}}
{{#INCLUDE_KEY_VAULT}}
output keyVaultName string = keyVault.outputs.name
output keyVaultUri string = keyVault.outputs.uri
{{/INCLUDE_KEY_VAULT}}
{{#INCLUDE_APP_INSIGHTS}}
output appInsightsName string = appInsights.outputs.name
output appInsightsInstrumentationKey string = appInsights.outputs.instrumentationKey
{{/INCLUDE_APP_INSIGHTS}}
{{#INCLUDE_FUNCTION_APP}}
output functionAppName string = functionApp.outputs.name
output functionAppUrl string = 'https://${functionApp.outputs.defaultHostname}'
{{/INCLUDE_FUNCTION_APP}}
