// Custom Wrapper Module for {{RESOURCE_TYPE}}
// Generated by Claude Code skill:generate-azure-bicep
// Wraps AVM module with project-specific defaults

@description('Resource name')
param name string

@description('Azure region')
param location string

@description('Environment name')
param environment string

@description('Resource tags')
param tags object = {}

// Combine project tags with provided tags
var allTags = union(tags, {
  project: '{{PROJECT_NAME}}'
  managedBy: 'bicep-avm'
  environment: environment
})

// AVM Module Reference
module {{RESOURCE_VAR_NAME}} 'br/public:avm/res/{{AVM_MODULE_PATH}}:{{MODULE_VERSION}}' = {
  name: '{{RESOURCE_VAR_NAME}}-${name}'
  params: {
    name: name
    location: location
    tags: allTags
    {{#DEFAULT_PARAMS}}
    {{PARAM_NAME}}: {{PARAM_VALUE}}
    {{/DEFAULT_PARAMS}}
  }
}

// Outputs
output resourceId string = {{RESOURCE_VAR_NAME}}.outputs.resourceId
output name string = {{RESOURCE_VAR_NAME}}.outputs.name
