#!/bin/bash
# Context health audit - run on demand
#
# Usage: bash context_freshness.sh [forge_plugin_dir]
#
# Checks:
# 1. Scan context .md files for HTTP links and test accessibility
# 2. Find context files not referenced by any SKILL.md (orphaned)
# 3. Flag context files with no "Last Updated" or older than 6 months
# 4. Generate report to /claudedocs/context_health_{date}.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FORGE_DIR="${1:-$(dirname "$SCRIPT_DIR")}"
CONTEXT_DIR="$FORGE_DIR/context"
SKILLS_DIR="$FORGE_DIR/skills"
TODAY=$(date +%Y-%m-%d)
SIX_MONTHS_AGO=$(date -d "6 months ago" +%Y-%m-%d 2>/dev/null || date -v-6m +%Y-%m-%d 2>/dev/null || echo "2025-08-10")

# Determine output directory
REPO_ROOT=$(git -C "$FORGE_DIR" rev-parse --show-toplevel 2>/dev/null || dirname "$FORGE_DIR")
OUTPUT_DIR="$REPO_ROOT/claudedocs"
mkdir -p "$OUTPUT_DIR"
REPORT="$OUTPUT_DIR/context_health_${TODAY}.md"

{
    echo "# Context Health Report"
    echo ""
    echo "**Generated**: $TODAY"
    echo "**Scope**: $CONTEXT_DIR"
    echo ""

    # Check 1: Files without "Last Updated" timestamp
    echo "## Freshness Check"
    echo ""
    STALE_COUNT=0
    while IFS= read -r file; do
        [[ -z "$file" ]] && continue
        REL_PATH="${file#$FORGE_DIR/}"
        LAST_UPDATED=$(grep -oP 'Last Updated:?\s*\K[0-9]{4}-[0-9]{2}-[0-9]{2}' "$file" 2>/dev/null | tail -1 || echo "")
        if [[ -z "$LAST_UPDATED" ]]; then
            echo "- **No timestamp**: \`$REL_PATH\`"
            STALE_COUNT=$((STALE_COUNT + 1))
        elif [[ "$LAST_UPDATED" < "$SIX_MONTHS_AGO" ]]; then
            echo "- **Stale** (last updated $LAST_UPDATED): \`$REL_PATH\`"
            STALE_COUNT=$((STALE_COUNT + 1))
        fi
    done < <(find "$CONTEXT_DIR" -name "*.md" -type f 2>/dev/null)

    if [[ "$STALE_COUNT" -eq 0 ]]; then
        echo "All context files have recent timestamps."
    fi
    echo ""

    # Check 2: Orphaned files (not referenced by any SKILL.md)
    echo "## Orphan Check"
    echo ""
    ORPHAN_COUNT=0
    while IFS= read -r file; do
        [[ -z "$file" ]] && continue
        BASENAME=$(basename "$file")
        [[ "$BASENAME" == "index.md" ]] && continue  # Index files are OK
        REL_PATH="${file#$FORGE_DIR/}"
        if ! grep -r "$BASENAME" "$SKILLS_DIR" --include="*.md" -q 2>/dev/null; then
            if ! grep -r "$BASENAME" "$CONTEXT_DIR" --include="index.md" -q 2>/dev/null; then
                echo "- **Orphaned**: \`$REL_PATH\` (not referenced by any SKILL.md or context index)"
                ORPHAN_COUNT=$((ORPHAN_COUNT + 1))
            fi
        fi
    done < <(find "$CONTEXT_DIR" -name "*.md" -type f -not -name "index.md" 2>/dev/null)

    if [[ "$ORPHAN_COUNT" -eq 0 ]]; then
        echo "All context files are referenced."
    fi
    echo ""

    # Check 3: HTTP link check (non-blocking, just reports)
    echo "## Link Check"
    echo ""
    LINK_COUNT=0
    BROKEN_COUNT=0
    while IFS= read -r file; do
        [[ -z "$file" ]] && continue
        LINKS=$(grep -oP 'https?://[^\s\)>]+' "$file" 2>/dev/null || true)
        for link in $LINKS; do
            LINK_COUNT=$((LINK_COUNT + 1))
            # Only check first 20 links to stay fast
            if [[ "$LINK_COUNT" -le 20 ]]; then
                HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "$link" 2>/dev/null || echo "000")
                if [[ "$HTTP_CODE" != "200" ]] && [[ "$HTTP_CODE" != "301" ]] && [[ "$HTTP_CODE" != "302" ]]; then
                    REL_PATH="${file#$FORGE_DIR/}"
                    echo "- **HTTP $HTTP_CODE**: \`$link\` in \`$REL_PATH\`"
                    BROKEN_COUNT=$((BROKEN_COUNT + 1))
                fi
            fi
        done
    done < <(find "$CONTEXT_DIR" -name "*.md" -type f 2>/dev/null)

    echo ""
    echo "Checked $((LINK_COUNT > 20 ? 20 : LINK_COUNT)) of $LINK_COUNT links found. $BROKEN_COUNT issues detected."
    echo ""

    # Summary
    echo "## Summary"
    echo ""
    TOTAL_FILES=$(find "$CONTEXT_DIR" -name "*.md" -type f 2>/dev/null | wc -l)
    echo "| Metric | Count |"
    echo "|--------|-------|"
    echo "| Total context files | $TOTAL_FILES |"
    echo "| Stale/missing timestamp | $STALE_COUNT |"
    echo "| Orphaned files | $ORPHAN_COUNT |"
    echo "| Broken links | $BROKEN_COUNT |"
    echo ""
    echo "---"
    echo "*Generated by context_freshness.sh*"

} > "$REPORT"

echo "Context health report saved to: $REPORT"
echo "Summary: $STALE_COUNT stale, $ORPHAN_COUNT orphaned, $BROKEN_COUNT broken links"
