name: Feature request
description: Propose an enhancement with clear user value.
title: "[feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem and value clearly so we can prioritize effectively.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What limitation or gap are you experiencing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Expected benefits
      description: Why is this valuable?
      placeholder: User impact, reliability, velocity, maintainability, cost.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you evaluate?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What outcomes would define this as done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2

