name: Security vulnerability
description: Security concerns must be reported privately per policy.
title: "[security] "
labels:
  - security
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Do not disclose exploit details publicly.

        Please follow the private disclosure process in `SECURITY.md`:
        - Security policy: `SECURITY.md`
        - Security advisories: https://github.com/Olino3/forge/security/advisories

        Use this form only for non-sensitive coordination (for example: policy clarification).
  - type: checkboxes
    id: acknowledgement
    attributes:
      label: Disclosure acknowledgement
      options:
        - label: I have read SECURITY.md and will report sensitive details privately.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Non-sensitive summary
      description: Provide only high-level context (no exploit steps, no secrets).
  - type: input
    id: contact
    attributes:
      label: Preferred secure contact channel
      placeholder: GitHub advisory thread, maintainer contact, etc.

