#!/bin/sh
# Initialize Azurite storage emulator with required containers, queues, and tables
# Generated by Claude Code skill:generate-azure-functions
# Project: {{PROJECT_NAME}}

set -e

echo "Initializing Azurite storage emulator..."

# Wait for Azurite to be ready
echo "Waiting for Azurite to be ready..."
for i in $(seq 1 30); do
  if nc -z 127.0.0.1 10000 2>/dev/null; then
    echo "Azurite is ready!"
    break
  fi
  echo "Waiting... ($i/30)"
  sleep 2
done

# Activate virtual environment and run Python initialization script
export PATH="/opt/venv/bin:$PATH"

# Get the Azurite account key from environment variable
AZURITE_KEY="${AZURITE_ACCOUNT_KEY:-Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==}"

/opt/venv/bin/python3 << 'EOF'
import sys
import os
from azure.storage.blob import BlobServiceClient
from azure.storage.queue import QueueServiceClient
from azure.data.tables import TableServiceClient

# Connection string for local Azurite using environment variable for the key
account_key = os.environ.get('AZURITE_KEY', 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==')
conn_string = f"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey={account_key};BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1"

print("=" * 70)
print("{{PROJECT_NAME_UPPER}} AZURITE INITIALIZATION")
print("=" * 70)

# ============================================================================
# Blob Containers
# ============================================================================
print("\n[1/3] Creating blob containers...")
try:
    blob_service = BlobServiceClient.from_connection_string(conn_string)

    containers = [
{{#BLOB_CONTAINERS}}
        ("{{NAME}}", "{{DESCRIPTION}}"),
{{/BLOB_CONTAINERS}}
    ]

    for container_name, description in containers:
        try:
            blob_service.create_container(container_name)
            print(f"  ✓ '{container_name}' created - {description}")
        except Exception as e:
            if "ContainerAlreadyExists" in str(e):
                print(f"  ✓ '{container_name}' already exists - {description}")
            else:
                print(f"  ✗ Error creating container '{container_name}': {e}")
                raise
except Exception as e:
    print(f"❌ Error with blob service: {e}")
    sys.exit(1)

# ============================================================================
# Queues
# ============================================================================
print("\n[2/3] Creating queues...")
try:
    queue_service = QueueServiceClient.from_connection_string(conn_string)

    queues = [
{{#QUEUES}}
        ("{{NAME}}", "{{DESCRIPTION}}"),
{{/QUEUES}}
    ]

    for queue_name, description in queues:
        try:
            queue_service.create_queue(queue_name)
            print(f"  ✓ '{queue_name}' created - {description}")
        except Exception as e:
            if "QueueAlreadyExists" in str(e):
                print(f"  ✓ '{queue_name}' already exists - {description}")
            else:
                print(f"  ✗ Error creating queue '{queue_name}': {e}")
except Exception as e:
    print(f"❌ Error with queue service: {e}")
    sys.exit(1)

# ============================================================================
# Tables
# ============================================================================
print("\n[3/3] Creating tables...")
try:
    table_service = TableServiceClient.from_connection_string(conn_string)

    tables = [
{{#TABLES}}
        ("{{NAME}}", "{{DESCRIPTION}}"),
{{/TABLES}}
    ]

    created_count = 0
    for table_name, description in tables:
        try:
            table_service.create_table(table_name)
            print(f"  ✓ '{table_name}' created - {description}")
            created_count += 1
        except Exception as e:
            if "TableAlreadyExists" in str(e):
                print(f"  ✓ '{table_name}' already exists - {description}")
            else:
                print(f"  ✗ Error creating table '{table_name}': {e}")
                raise

    print(f"\n  Summary: {created_count} new tables created, {len(tables)} total tables available")

except Exception as e:
    print(f"❌ Error with table service: {e}")
    sys.exit(1)

# ============================================================================
# Summary
# ============================================================================
print("\n" + "=" * 70)
print("✅ AZURITE INITIALIZATION COMPLETE!")
print("=" * 70)
print("\nResources created:")
print(f"  • Blob containers: {{BLOB_CONTAINER_COUNT}}")
print(f"  • Queues: {{QUEUE_COUNT}}")
print(f"  • Tables: {{TABLE_COUNT}}")
print("\nConnection string for testing:")
print(f"  DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;...")
print("=" * 70 + "\n")

EOF

echo "Initialization script completed successfully!"
