#!/usr/bin/env python3
"""
Bicep Generator Utilities
Generated by Claude Code skill:generate-azure-bicep
"""

from typing import Dict, List, Tuple
import re


def get_avm_module_path(resource_type: str) -> Tuple[str, str]:
    """
    Get AVM module path and latest stable version for a resource type.

    Args:
        resource_type: Azure resource type (storage-account, key-vault, function-app, etc.)

    Returns:
        Tuple of (module_path, recommended_version)
    """
    avm_modules = {
        "storage-account": ("avm/res/storage/storage-account", "0.9.0"),
        "key-vault": ("avm/res/key-vault/vault", "0.6.0"),
        "function-app": ("avm/res/web/site", "0.3.0"),
        "app-service": ("avm/res/web/site", "0.3.0"),
        "app-service-plan": ("avm/res/web/serverfarm", "0.2.0"),
        "virtual-network": ("avm/res/network/virtual-network", "0.1.0"),
        "sql-server": ("avm/res/sql/server", "0.6.0"),
        "cosmos-db": ("avm/res/document-db/database-account", "0.7.0"),
        "container-registry": ("avm/res/container-registry/registry", "0.3.0"),
        "log-analytics": ("avm/res/operational-insights/workspace", "0.3.0"),
        "app-insights": ("avm/res/insights/component", "0.3.0"),
    }

    return avm_modules.get(resource_type, ("", "0.1.0"))


def get_resource_abbreviation(resource_type: str) -> str:
    """
    Get Azure resource abbreviation for naming.

    Args:
        resource_type: Resource type

    Returns:
        Abbreviation (e.g., 'st' for storage-account)
    """
    abbreviations = {
        "storage-account": "st",
        "key-vault": "kv",
        "function-app": "func",
        "app-service": "app",
        "app-service-plan": "plan",
        "virtual-network": "vnet",
        "sql-server": "sql",
        "cosmos-db": "cosmos",
        "container-registry": "acr",
        "log-analytics": "logs",
        "app-insights": "appi",
        "resource-group": "rg",
    }

    return abbreviations.get(resource_type, resource_type[:4])


def generate_resource_name(resource_type: str, environment: str, region: str = None, unique_suffix: bool = False) -> str:
    """
    Generate Azure resource name following conventions.

    Args:
        resource_type: Type of resource
        environment: Environment (dev, staging, prod)
        region: Azure region (optional)
        unique_suffix: Whether to include unique suffix placeholder

    Returns:
        Resource name pattern
    """
    abbr = get_resource_abbreviation(resource_type)
    parts = [abbr, environment]

    if region:
        parts.append(region)

    name = "-".join(parts)

    if unique_suffix:
        name += "-${uniqueString(resourceGroup().id)}"

    return name


def validate_bicep_config(config: Dict) -> List[str]:
    """
    Validate Bicep configuration.

    Args:
        config: Configuration dictionary

    Returns:
        List of validation errors (empty if valid)
    """
    errors = []

    required_fields = ["project_name", "environments", "resources"]
    for field in required_fields:
        if field not in config:
            errors.append(f"Missing required field: {field}")

    if "resources" in config and not isinstance(config["resources"], list):
        errors.append("Resources must be a list")

    if "resources" in config and len(config["resources"]) == 0:
        errors.append("At least one resource is required")

    if "environments" in config and len(config["environments"]) == 0:
        errors.append("At least one environment is required")

    return errors


def get_sku_by_environment(resource_type: str, environment: str) -> str:
    """
    Get recommended SKU for resource type and environment.

    Args:
        resource_type: Azure resource type
        environment: Environment name

    Returns:
        SKU name
    """
    is_prod = environment.lower() in ["production", "prod"]

    skus = {
        "storage-account": "Standard_GRS" if is_prod else "Standard_LRS",
        "key-vault": "premium" if is_prod else "standard",
        "app-service-plan": "P1v2" if is_prod else "B1",
        "sql-database": "S1" if is_prod else "Basic",
        "cosmos-db": "Standard" if is_prod else "Standard",
    }

    return skus.get(resource_type, "Standard")


def get_deployment_scope(scope_type: str) -> Tuple[str, str]:
    """
    Get deployment scope and CLI command format.

    Args:
        scope_type: Scope type (subscription, resource-group, etc.)

    Returns:
        Tuple of (targetScope_value, cli_scope_name)
    """
    scopes = {
        "subscription": ("subscription", "sub"),
        "resource-group": ("resourceGroup", "group"),
        "management-group": ("managementGroup", "mg"),
        "tenant": ("tenant", "tenant"),
    }

    return scopes.get(scope_type, ("resourceGroup", "group"))


def generate_bicepparams_content(project_name: str, environment: str, location: str, resource_prefix: str) -> str:
    """
    Generate bicepparams file content.

    Args:
        project_name: Project name
        environment: Environment name
        location: Azure region
        resource_prefix: Resource naming prefix

    Returns:
        Bicepparams file content
    """
    return f"""// Bicep Parameters for {project_name} - {environment.title()} Environment
// Generated by Claude Code skill:generate-azure-bicep

using './main.bicep'

param environment = '{environment}'
param location = '{location}'
param resourcePrefix = '{resource_prefix}'
"""


def get_unique_string_input(scope_type: str) -> str:
    """
    Get the appropriate input for uniqueString() based on scope.

    Args:
        scope_type: Deployment scope

    Returns:
        Expression for uniqueString input
    """
    if scope_type == "subscription":
        return "subscription().id"
    elif scope_type == "resource-group":
        return "resourceGroup().id"
    elif scope_type == "management-group":
        return "managementGroup().id"
    else:
        return "resourceGroup().id"


if __name__ == "__main__":
    # Example usage
    print("Bicep Generator Utilities")
    print("=" * 50)

    # Example: Get AVM module path
    module_path, version = get_avm_module_path("storage-account")
    print(f"Storage Account AVM: br/public:{module_path}:{version}")

    # Example: Generate resource name
    name = generate_resource_name("storage-account", "production", unique_suffix=True)
    print(f"Storage name pattern: {name}")

    # Example: Get SKU
    sku = get_sku_by_environment("storage-account", "production")
    print(f"Production SKU: {sku}")

    # Example: Deployment scope
    target_scope, cli_scope = get_deployment_scope("subscription")
    print(f"Target scope: {target_scope}, CLI: az deployment {cli_scope}")
