// Main Bicep Template for {{PROJECT_NAME}}
// Generated by Claude Code skill:generate-azure-pipelines

targetScope = 'subscription'

@description('The environment name (development, staging, production)')
param environment string

@description('The Azure region for all resources')
param location string = '{{DEFAULT_LOCATION}}'

@description('Resource name prefix')
param resourcePrefix string = '{{RESOURCE_PREFIX}}'

// Variables
var resourceGroupName = '${resourcePrefix}-${environment}-rg'
var tags = {
  environment: environment
  project: '{{PROJECT_NAME}}'
  managedBy: 'bicep'
}

// Resource Group
resource rg 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

{{#INCLUDE_STORAGE}}
// Storage Account Module
module storageAccount './modules/storage-account.bicep' = {
  name: 'storageAccount'
  scope: rg
  params: {
    location: location
    environment: environment
    tags: tags
    storageAccountName: '{{STORAGE_ACCOUNT_PREFIX}}${uniqueString(rg.id)}'
  }
}

{{/INCLUDE_STORAGE}}
{{#INCLUDE_FUNCTION_APP}}
// Function App Module
module functionApp './modules/function-app.bicep' = {
  name: 'functionApp'
  scope: rg
  params: {
    location: location
    environment: environment
    tags: tags
    functionAppName: '{{FUNCTION_APP_PREFIX}}-${environment}'
    {{#INCLUDE_STORAGE}}
    storageAccountName: storageAccount.outputs.storageAccountName
    {{/INCLUDE_STORAGE}}
    {{#INCLUDE_APP_INSIGHTS}}
    appInsightsInstrumentationKey: appInsights.outputs.instrumentationKey
    {{/INCLUDE_APP_INSIGHTS}}
  }
}

{{/INCLUDE_FUNCTION_APP}}
{{#INCLUDE_APP_SERVICE}}
// App Service Module
module appService './modules/app-service.bicep' = {
  name: 'appService'
  scope: rg
  params: {
    location: location
    environment: environment
    tags: tags
    appServiceName: '{{APP_SERVICE_PREFIX}}-${environment}'
    {{#INCLUDE_APP_INSIGHTS}}
    appInsightsInstrumentationKey: appInsights.outputs.instrumentationKey
    {{/INCLUDE_APP_INSIGHTS}}
  }
}

{{/INCLUDE_APP_SERVICE}}
{{#INCLUDE_KEY_VAULT}}
// Key Vault Module
module keyVault './modules/key-vault.bicep' = {
  name: 'keyVault'
  scope: rg
  params: {
    location: location
    environment: environment
    tags: tags
    keyVaultName: '{{KEY_VAULT_PREFIX}}-${environment}-${uniqueString(rg.id)}'
  }
}

{{/INCLUDE_KEY_VAULT}}
{{#INCLUDE_APP_INSIGHTS}}
// Application Insights Module
module appInsights './modules/app-insights.bicep' = {
  name: 'appInsights'
  scope: rg
  params: {
    location: location
    environment: environment
    tags: tags
    appInsightsName: '{{APP_INSIGHTS_PREFIX}}-${environment}'
  }
}

{{/INCLUDE_APP_INSIGHTS}}
{{#INCLUDE_SQL_DATABASE}}
// SQL Database Module
module sqlDatabase './modules/sql-database.bicep' = {
  name: 'sqlDatabase'
  scope: rg
  params: {
    location: location
    environment: environment
    tags: tags
    sqlServerName: '{{SQL_SERVER_PREFIX}}-${environment}-${uniqueString(rg.id)}'
    databaseName: '{{DATABASE_NAME}}'
  }
}

{{/INCLUDE_SQL_DATABASE}}
{{#INCLUDE_COSMOS_DB}}
// Cosmos DB Module
module cosmosDb './modules/cosmos-db.bicep' = {
  name: 'cosmosDb'
  scope: rg
  params: {
    location: location
    environment: environment
    tags: tags
    cosmosDbAccountName: '{{COSMOS_DB_PREFIX}}-${environment}-${uniqueString(rg.id)}'
  }
}

{{/INCLUDE_COSMOS_DB}}

// Outputs
output resourceGroupName string = rg.name
output resourceGroupId string = rg.id
{{#INCLUDE_STORAGE}}
output storageAccountName string = storageAccount.outputs.storageAccountName
{{/INCLUDE_STORAGE}}
{{#INCLUDE_FUNCTION_APP}}
output functionAppName string = functionApp.outputs.functionAppName
output functionAppUrl string = functionApp.outputs.functionAppUrl
{{/INCLUDE_FUNCTION_APP}}
{{#INCLUDE_APP_SERVICE}}
output appServiceName string = appService.outputs.appServiceName
output appServiceUrl string = appService.outputs.appServiceUrl
{{/INCLUDE_APP_SERVICE}}
{{#INCLUDE_KEY_VAULT}}
output keyVaultName string = keyVault.outputs.keyVaultName
{{/INCLUDE_KEY_VAULT}}
{{#INCLUDE_APP_INSIGHTS}}
output appInsightsName string = appInsights.outputs.appInsightsName
{{/INCLUDE_APP_INSIGHTS}}
